#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebAPI.Context;
using WebAPI.Models;

using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;

using BCryptNet = BCrypt.Net.BCrypt;
using System.Text.RegularExpressions;

namespace WebAPI.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class UserController : ControllerBase
    {
        private readonly DatabaseContext _context;
        private readonly IConfiguration configuration;

        public UserController(DatabaseContext context, IConfiguration iConfig)
        {
            _context = context;
            configuration = iConfig;
        }

        /// <summary>
        /// Takes a user object from the webservice.
        /// Returns NotFound if username or password cannot be validated by the same method they were during registration.
        /// Returns NotFound if username or password is incorrect.
        /// Otherwise, returns a JWT Token.
        /// </summary>
        /// <param name="loginUser"></param>
        /// <returns></returns>
        // POST: api/User/Login
        [HttpPost("Login")]
        public async Task<ActionResult<User>> LoginUser(User loginUser)
        {
            //Validate User info before interacting with database
            if (ValidateUserInfo(loginUser) == false)
            {
                return NotFound("User info not correct");
            }

            //var user = await _context.Users.FirstOrDefaultAsync(u => u.Username == loginUser.Username);
            var user = (await _context.Users.Where(u => u.username == loginUser.username).ToListAsync()).FirstOrDefault(u => u.username == loginUser.username); //Case sensitivity hack

            if ((user == null) || (!BCryptNet.Verify(loginUser.password, user.password)))
            {
                return NotFound("User info not correct");
            }

            string key = configuration.GetValue<string>("Jwt:Key"); //Secret key which will be used later during validation
            string issuer = configuration.GetValue<string>("Jwt:Issuer");
            string audience = configuration.GetValue<string>("Jwt:Audience");

            var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(key));
            var credentials = new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256);

            //List of claims for token to include. For this system, only userId in necessary.
            var permClaims = new List<Claim>();
            permClaims.Add(new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()));
            permClaims.Add(new Claim("userId", user.userId.ToString()));

            //Create JSON Web Token.
            var token = new JwtSecurityToken(issuer,
                            audience,
                            permClaims,
                            expires: DateTime.Now.AddDays(31), //A token generated by this system will last 31 days.
                            signingCredentials: credentials);
            var jwt_token = new JwtSecurityTokenHandler().WriteToken(token);

            return Ok(jwt_token);
        }

        /// <summary>
        /// Takes a user object from the webservice.
        /// Returns Forbid if username or password cannot be validated by the same parameters they would be before leaving the app.
        /// Returns Conflict if username already exists.
        /// Otherwise, adds user to database and returns Status Code 201.
        /// </summary>
        /// <param name="registerUser"></param>
        /// <returns></returns>
        // POST: api/User/Register
        [HttpPost("Register")]
        public async Task<ActionResult<User>> RegisterUser(User registerUser)
        {
            //Validate User info before interacting with database
            if (ValidateUserInfo(registerUser) == false)
            {
                return Forbid();
            }

            //var user = await _context.Users.FirstOrDefaultAsync(u => u.username == registerUser.username);
            var user = (await _context.Users.Where(u => u.username == registerUser.username).ToListAsync()).FirstOrDefault(u => u.username == registerUser.username); //Case sensitivity hack

            if (user != null)
            {
                return Conflict("Username already registered");
            }

            registerUser.password = BCryptNet.HashPassword(registerUser.password, BCryptNet.GenerateSalt());

            _context.Users.Add(registerUser);
            await _context.SaveChangesAsync();

            return StatusCode(201);
        }

#if debug //if preventing the inclusion of the code contained in a release build.
        /// <summary>
        /// Takes a user object.
        /// Returns Forbid if username or password cannot be validated.
        /// Returns NotFound if username incorrect.
        /// Otherwise, changes user password in dtabase and returns Status Code 201.
        /// Only for emergency use (such as when password validation is introduced mid-project), and NEVER for release!
        /// </summary>
        /// <param name="registerUser"></param>
        /// <returns></returns>
        // POST: api/User/Register
        //[HttpPost("Alter")]
        //public async Task<ActionResult<User>> AlterUser(User alterUser)
        //{
        //    //Validate User info before interacting with database
        //    if (ValidateUserInfo(alterUser) == false)
        //    {
        //        return Forbid();
        //    }

        //    //var user = await _context.Users.FirstOrDefaultAsync(u => u.username == alterUser.username);
        //    var user = (await _context.Users.Where(u => u.username == alterUser.username).ToListAsync()).FirstOrDefault(u => u.username == alterUser.username); //Case sensitivity hack

        //    if (user == null)
        //    {
        //        return NotFound("User info not correct");
        //    }

        //    user.password = BCryptNet.HashPassword(alterUser.password, BCryptNet.GenerateSalt());

        //    _context.Users.Update(user);
        //    await _context.SaveChangesAsync();

        //    return StatusCode(201);
        //}
#endif

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.userId == id);
        }

        //Validates user info with same checks as client
        //Client side is faster for user, instead of making a call for every attempt
        //Server side is for extra security
        public static bool ValidateUserInfo(User user)
        {
            //Could be one long statement, but this makes debugging somewhat easier
            if (user.username == "" ||
                user.username.Length < 6 ||
                user.username.Length > 30)
            {
                return false;
            }
            if (!Regex.Match(user.username, "^[a-zA-Z0-9-@._!?]+$").Success)
            {
                return false;
            }
            if (user.password == "" ||
                user.password.Length < 8 ||
                user.password.Length > 99)
            {
                return false;
            }
            if (!Regex.Match(user.password, ".*[A-Z].*").Success ||
                !Regex.Match(user.password, ".*[a-z].*").Success ||
                !Regex.Match(user.password, ".*[0-9-@._!?].*").Success ||
                !Regex.Match(user.password, "^[a-zA-Z0-9-@._!?]+$").Success)
            {
                return false;
            }

            return true;
        }
    }
}
